name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.14.2-slim
    env:
      MIX_ENV: test
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        mix local.hex --force
        mix local.rebar --force
        mix deps.get
    - name: Run Tests
      run: mix test